repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/psf/black
    rev: 22.3.0
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://github.com/pycqa/flake8
    rev: 4.0.1
